/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AISeatingSuggestion {
  'suggestionId' : string,
  'date' : string,
  'createdAt' : bigint,
  'reasoning' : string,
  'zonePreference' : [] | [string],
  'partySize' : bigint,
  'confidence' : number,
  'suggestedTableIds' : Array<string>,
}
export interface AuditLogEntry {
  'id' : string,
  'action' : string,
  'oldValue' : [] | [string],
  'callerName' : string,
  'callerRole' : string,
  'page' : string,
  'newValue' : [] | [string],
  'summary' : string,
  'timestamp' : bigint,
  'callerPrincipal' : string,
}
export interface AvailableSlotsResponse {
  'fixedClosingDays' : Array<bigint>,
  'slots' : Array<TimeSlot>,
}
export interface BrandingSettings {
  'confirmationText' : string,
  'primaryColor' : string,
  'accentColor' : string,
  'logoUrl' : [] | [string],
  'defaultLanguage' : string,
  'welcomeText' : string,
}
export interface ClosingDay {
  'date' : string,
  'serviceId' : [] | [string],
  'reason' : string,
}
export interface CustomQuestion {
  'id' : string,
  'labelText' : string,
  'questionType' : { 'text' : null } |
    { 'dropdown' : null },
  'required' : boolean,
  'options' : Array<string>,
}
export type DayOfWeek = bigint;
export interface EmailTemplate {
  'id' : string,
  'backgroundColor' : string,
  'subject' : string,
  'heading' : string,
  'templateType' : EmailTemplateType,
  'accentColor' : string,
  'logoUrl' : string,
  'bodyHtml' : string,
  'footer' : string,
}
export type EmailTemplateType = string;
export interface Experience {
  'id' : ExperienceId,
  'maxCapacity' : bigint,
  'dayOfWeek' : [] | [Array<bigint>],
  'name' : string,
  'pricePerPerson' : bigint,
  'description' : string,
  'isActive' : boolean,
  'serviceIds' : [] | [Array<string>],
  'required' : boolean,
}
export type ExperienceId = string;
export interface FloorState { 'tables' : Array<Table>, 'updatedAt' : Timestamp }
export interface Guest {
  'id' : GuestId,
  'reservationIds' : Array<ReservationId>,
  'name' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'email' : string,
  'phone' : [] | [string],
}
export interface GuestFormSettings {
  'requireAllergies' : boolean,
  'requireDietPreferences' : boolean,
  'requirePhone' : boolean,
  'showBabiesChildren' : boolean,
  'customQuestions' : Array<CustomQuestion>,
}
export type GuestId = string;
export interface IntegrationSettings {
  'mollieEnabled' : boolean,
  'calendarSyncEnabled' : boolean,
  'stripePublicKey' : string,
  'stripeEnabled' : boolean,
  'apiKey' : string,
  'posSystem' : [] | [string],
}
export interface KPIs {
  'avgPartySize' : bigint,
  'occupancyPct' : bigint,
  'todayCoversPerService' : Array<[string, bigint]>,
  'waitlistCount' : bigint,
  'todayReservationCount' : bigint,
  'noShowCount' : bigint,
}
export interface NotificationSettings {
  'sendReminderEmail' : boolean,
  'waitlistAutoActivate' : boolean,
  'sendCancellationEmail' : boolean,
  'reminderHoursBefore' : Array<bigint>,
  'sendConfirmationEmail' : boolean,
}
export interface OccupancySettings {
  'globalCeilingPercent' : bigint,
  'maxGuestsPerReservationMax' : bigint,
  'maxGuestsPerReservationMin' : bigint,
}
export interface Reservation {
  'id' : ReservationId,
  'status' : ReservationStatus,
  'experienceId' : [] | [ExperienceId],
  'date' : string,
  'specialRequests' : [] | [string],
  'createdAt' : Timestamp,
  'time' : string,
  'zone' : [] | [string],
  'tableId' : [] | [string],
  'updatedAt' : Timestamp,
  'notes' : [] | [string],
  'stripePaymentIntentId' : [] | [string],
  'partySize' : bigint,
  'changes' : Array<ReservationChange>,
  'guestId' : GuestId,
}
export interface ReservationChange {
  'id' : string,
  'field' : string,
  'changedByName' : string,
  'changedByRole' : string,
  'oldValue' : string,
  'changedBy' : string,
  'newValue' : string,
  'timestamp' : bigint,
}
export interface ReservationFilter {
  'status' : [] | [ReservationStatus],
  'date' : [] | [string],
  'time' : [] | [string],
  'guestId' : [] | [GuestId],
}
export type ReservationId = string;
export interface ReservationRules {
  'maxStayMinutesDinner' : bigint,
  'maxPartySize' : bigint,
  'maxStayMinutesLunch' : bigint,
  'advanceBookingDays' : bigint,
  'noShowFeeEur' : bigint,
  'minPartySize' : bigint,
  'depositAmountEur' : bigint,
  'depositRequiredAbovePartySize' : bigint,
  'depositRequired' : boolean,
  'cancellationHoursBeforeFree' : bigint,
}
export type ReservationStatus = { 'cancelled' : null } |
  { 'late' : null } |
  { 'seated' : null } |
  { 'waitlist' : null } |
  { 'departed' : null } |
  { 'confirmed' : null } |
  { 'not_arrived' : null };
export interface ReservationSummary {
  'date' : string,
  'time' : string,
  'tableId' : string,
  'partySize' : bigint,
}
export interface RestaurantExtendedConfig {
  'timezone' : string,
  'integrations' : IntegrationSettings,
  'notifications' : NotificationSettings,
  'openingHour' : bigint,
  'guestForm' : GuestFormSettings,
  'fixedClosingDays' : Array<DayOfWeek>,
  'logoUrl' : [] | [string],
  'zones' : Array<ZoneCapacity>,
  'tableTypes' : Array<TableType>,
  'reservationRules' : ReservationRules,
  'zoneDefs' : Array<Zone>,
  'currency' : string,
  'restaurantName' : string,
  'closingHour' : bigint,
  'contactEmail' : string,
  'occupancySettings' : [] | [OccupancySettings],
  'branding' : BrandingSettings,
  'exceptionalClosingDays' : Array<ClosingDay>,
  'services' : Array<ServiceHours>,
  'totalSeatsPerSlot' : bigint,
  'slotIntervalMinutes' : bigint,
  'contactPhone' : string,
}
export type ReviewRequestDelay = { 'hour1' : null } |
  { 'hour2' : null } |
  { 'hour24' : null };
export interface ReviewRequestSettings {
  'enabled' : boolean,
  'message' : string,
  'delay' : ReviewRequestDelay,
}
export interface SeasonalPeriod {
  'id' : string,
  'dateTo' : string,
  'autoActivate' : boolean,
  'name' : string,
  'capacityOverride' : [] | [bigint],
  'activatedZones' : Array<string>,
  'isActive' : boolean,
  'dateFrom' : string,
}
export interface ServiceHours {
  'id' : string,
  'closeTime' : string,
  'maxCapacity' : bigint,
  'name' : string,
  'openTime' : string,
  'enabledDays' : Array<DayOfWeek>,
}
export interface SuggestionAccuracyStats {
  'periodDays' : bigint,
  'acceptedCount' : bigint,
  'acceptanceRatePct' : number,
  'totalSuggestions' : bigint,
  'rejectedCount' : bigint,
}
export interface Table {
  'x' : bigint,
  'y' : bigint,
  'id' : TableId,
  'status' : TableStatus,
  'name' : string,
  'zone' : [] | [string],
  'seatCount' : [] | [bigint],
  'guestName' : [] | [string],
  'groupId' : [] | [string],
  'capacity' : bigint,
  'reservationId' : [] | [ReservationId],
}
export interface TableAssignment {
  'assignedAt' : Timestamp,
  'seatCount' : bigint,
  'tableId' : TableId,
  'guestName' : string,
  'reservationId' : ReservationId,
}
export interface TableGroupDefinition {
  'id' : string,
  'name' : string,
  'tableIds' : Array<string>,
  'description' : string,
  'totalCapacity' : bigint,
}
export type TableId = string;
export type TableStatus = { 'occupied' : null } |
  { 'reserved' : null } |
  { 'empty' : null } |
  { 'unavailable' : null };
export interface TableType {
  'count' : bigint,
  'typeName' : string,
  'capacity' : bigint,
}
export interface TeamMember {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'email' : string,
  'principalId' : string,
}
export interface TimeSlot {
  'status' : TimeSlotStatus,
  'time' : string,
  'totalSeats' : bigint,
  'availableSeats' : bigint,
}
export type TimeSlotStatus = { 'full' : null } |
  { 'available' : null } |
  { 'limited' : null };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WaitlistEntry {
  'id' : WaitlistId,
  'status' : WaitlistStatus,
  'date' : string,
  'joinedAt' : Timestamp,
  'notifiedAt' : [] | [Timestamp],
  'notes' : [] | [string],
  'requestedTime' : [] | [string],
  'partySize' : bigint,
  'guestId' : GuestId,
}
export type WaitlistId = string;
export type WaitlistStatus = { 'expired' : null } |
  { 'removed_by_staff' : null } |
  { 'confirmed' : null } |
  { 'offered' : null } |
  { 'waiting' : null };
export interface Zone {
  'id' : string,
  'boundaries' : [] | [string],
  'name' : string,
  'color' : string,
  'maxGuests' : bigint,
}
export interface ZoneCapacity { 'zoneName' : string, 'maxGuests' : bigint }
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addTeamMember' : ActorMethod<
    [string, string, string, string],
    { 'ok' : TeamMember } |
      { 'err' : string }
  >,
  'addToWaitlist' : ActorMethod<
    [GuestId, string, bigint, [] | [string], [] | [string]],
    { 'ok' : WaitlistEntry } |
      { 'err' : string }
  >,
  'addZone' : ActorMethod<
    [string, string, bigint],
    { 'ok' : Zone } |
      { 'err' : string }
  >,
  'applyHouseStyleToAll' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'askAI' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignReservationToTable' : ActorMethod<
    [TableId, ReservationId],
    { 'ok' : TableAssignment } |
      { 'err' : string }
  >,
  'assignReservationToTableWithDetails' : ActorMethod<
    [TableId, ReservationId, string, bigint],
    { 'ok' : TableAssignment } |
      { 'err' : string }
  >,
  'autoAssignTable' : ActorMethod<
    [ReservationId, bigint, string, string],
    { 'ok' : Table } |
      { 'err' : string }
  >,
  'cancelReservation' : ActorMethod<[ReservationId], undefined>,
  'createExperience' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      boolean,
      [] | [Array<string>],
      [] | [Array<bigint>],
    ],
    Experience
  >,
  'createGuest' : ActorMethod<[string, string, [] | [string]], Guest>,
  'createReservation' : ActorMethod<
    [
      GuestId,
      string,
      string,
      bigint,
      [] | [ExperienceId],
      [] | [string],
      [] | [string],
    ],
    Reservation
  >,
  'createReservationWithDetails' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [ExperienceId],
    ],
    { 'ok' : Reservation } |
      { 'err' : string }
  >,
  'createTable' : ActorMethod<
    [string, bigint, bigint, bigint, [] | [string]],
    { 'ok' : Table } |
      { 'err' : string }
  >,
  'createTableGroupDefinition' : ActorMethod<
    [string, Array<string>, string],
    { 'ok' : TableGroupDefinition } |
      { 'err' : string }
  >,
  'deleteSeasonalPeriod' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteTable' : ActorMethod<[TableId], { 'ok' : null } | { 'err' : string }>,
  'deleteTableGroupDefinition' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteZone' : ActorMethod<[string], { 'ok' : boolean } | { 'err' : string }>,
  'findBestTable' : ActorMethod<
    [bigint, string, string, Array<string>],
    [] | [Table]
  >,
  'findBestTableForReservation' : ActorMethod<
    [bigint, string, string],
    [] | [Table]
  >,
  'getAISuggestions' : ActorMethod<
    [[] | [GuestId], string],
    { 'ok' : Array<string> } |
      { 'err' : string }
  >,
  'getActiveSeason' : ActorMethod<[string], [] | [SeasonalPeriod]>,
  'getActiveZonesForDate' : ActorMethod<[string], Array<string>>,
  'getAuditLog' : ActorMethod<
    [],
    { 'ok' : Array<AuditLogEntry> } |
      { 'err' : string }
  >,
  'getAuditLogPaginated' : ActorMethod<
    [bigint, bigint],
    { 'ok' : { 'total' : bigint, 'entries' : Array<AuditLogEntry> } } |
      { 'err' : string }
  >,
  'getAvailableSlots' : ActorMethod<[string], AvailableSlotsResponse>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmailTemplates' : ActorMethod<[], Array<EmailTemplate>>,
  'getExtendedConfig' : ActorMethod<
    [],
    { 'ok' : RestaurantExtendedConfig } |
      { 'err' : string }
  >,
  'getFloorState' : ActorMethod<[], FloorState>,
  'getGuest' : ActorMethod<[GuestId], [] | [Guest]>,
  'getKPIs' : ActorMethod<[], KPIs>,
  'getReservation' : ActorMethod<[ReservationId], [] | [Reservation]>,
  'getReservationChanges' : ActorMethod<
    [ReservationId],
    { 'ok' : Array<ReservationChange> } |
      { 'err' : string }
  >,
  'getRestaurantConfig' : ActorMethod<
    [],
    {
      'openingHour' : bigint,
      'restaurantName' : string,
      'closingHour' : bigint,
      'totalSeatsPerSlot' : bigint,
      'slotIntervalMinutes' : bigint,
    }
  >,
  'getReviewRequestSettings' : ActorMethod<[], ReviewRequestSettings>,
  'getSeasonalPeriods' : ActorMethod<[], Array<SeasonalPeriod>>,
  'getSuggestionAccuracyStats' : ActorMethod<[bigint], SuggestionAccuracyStats>,
  'getTableGroupDefinitions' : ActorMethod<
    [],
    { 'ok' : Array<TableGroupDefinition> } |
      { 'err' : string }
  >,
  'getTables' : ActorMethod<[], Array<Table>>,
  'getWaitlist' : ActorMethod<[string], Array<WaitlistEntry>>,
  'getWaitlistEntry' : ActorMethod<[WaitlistId], [] | [WaitlistEntry]>,
  'getZones' : ActorMethod<[], { 'ok' : Array<Zone> } | { 'err' : string }>,
  'groupTables' : ActorMethod<
    [Array<string>, string],
    { 'ok' : Array<Table> } |
      { 'err' : string }
  >,
  'hasOwner' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveExperiences' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<Experience>
  >,
  'listExperiences' : ActorMethod<[], Array<Experience>>,
  'listGuests' : ActorMethod<[], Array<Guest>>,
  'listReservations' : ActorMethod<
    [ReservationFilter],
    { 'ok' : Array<Reservation> } |
      { 'err' : string }
  >,
  'listTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'logAuditEntry' : ActorMethod<
    [string, string, string, string, [] | [string], [] | [string]],
    undefined
  >,
  'offerWaitlistSpot' : ActorMethod<[WaitlistId], undefined>,
  'recordReviewRequestSent' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recordSuggestionFeedback' : ActorMethod<
    [string, boolean, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeTeamMember' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeWaitlistEntry' : ActorMethod<
    [WaitlistId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'reofferWaitlistSpot' : ActorMethod<
    [WaitlistId],
    { 'ok' : WaitlistEntry } |
      { 'err' : string }
  >,
  'resetEmailTemplate' : ActorMethod<
    [EmailTemplateType],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveEmailTemplate' : ActorMethod<
    [EmailTemplate],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveEmailTemplates' : ActorMethod<
    [Array<EmailTemplate>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveReviewRequestSettings' : ActorMethod<
    [boolean, ReviewRequestDelay, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveSeasonalPeriod' : ActorMethod<
    [SeasonalPeriod],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'searchGuests' : ActorMethod<
    [string, bigint, bigint],
    { 'total' : bigint, 'guests' : Array<Guest> }
  >,
  'setOwner' : ActorMethod<[Principal], undefined>,
  'setTableStatus' : ActorMethod<
    [TableId, TableStatus],
    { 'ok' : Table } |
      { 'err' : string }
  >,
  'shouldSendReviewRequest' : ActorMethod<[string], boolean>,
  'suggestTable' : ActorMethod<
    [bigint, [] | [string], string, string, Array<ReservationSummary>],
    { 'ok' : AISeatingSuggestion } |
      { 'err' : string }
  >,
  'syncTablesFromSettings' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'toggleSeasonalPeriod' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'unassignTable' : ActorMethod<
    [TableId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'ungroupTables' : ActorMethod<
    [string],
    { 'ok' : Array<Table> } |
      { 'err' : string }
  >,
  'updateBrandingSettings' : ActorMethod<
    [BrandingSettings],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCapacitySettings' : ActorMethod<
    [Array<ZoneCapacity>, Array<TableType>, [] | [OccupancySettings], bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateExceptionalClosingDays' : ActorMethod<
    [Array<DayOfWeek>, Array<ClosingDay>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateExperience' : ActorMethod<[Experience], undefined>,
  'updateGeneralInfo' : ActorMethod<
    [string, string, string, string, string, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateGuestFormSettings' : ActorMethod<
    [GuestFormSettings],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateGuestTags' : ActorMethod<[GuestId, Array<string>], undefined>,
  'updateIntegrationSettings' : ActorMethod<
    [IntegrationSettings],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateNotificationSettings' : ActorMethod<
    [NotificationSettings],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateReservation' : ActorMethod<
    [
      ReservationId,
      string,
      string,
      bigint,
      [] | [string],
      [] | [ReservationStatus],
      [] | [ExperienceId],
      [] | [string],
      [] | [string],
    ],
    { 'ok' : Reservation } |
      { 'err' : string }
  >,
  'updateReservationRules' : ActorMethod<
    [ReservationRules],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateReservationStatus' : ActorMethod<
    [ReservationId, ReservationStatus],
    undefined
  >,
  'updateRestaurantConfig' : ActorMethod<
    [string, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updateServiceHours' : ActorMethod<
    [Array<ServiceHours>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateTableCapacity' : ActorMethod<
    [TableId, bigint],
    { 'ok' : Table } |
      { 'err' : string }
  >,
  'updateTableGroupDefinition' : ActorMethod<
    [string, string, Array<string>, string],
    { 'ok' : TableGroupDefinition } |
      { 'err' : string }
  >,
  'updateTablePosition' : ActorMethod<
    [TableId, bigint, bigint],
    { 'ok' : Table } |
      { 'err' : string }
  >,
  'updateTableZone' : ActorMethod<
    [TableId, [] | [string]],
    { 'ok' : Table } |
      { 'err' : string }
  >,
  'updateTeamMemberRole' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateWaitlistEntry' : ActorMethod<
    [WaitlistId, bigint, [] | [string]],
    { 'ok' : WaitlistEntry } |
      { 'err' : string }
  >,
  'updateZone' : ActorMethod<
    [string, string, string, bigint],
    { 'ok' : Zone } |
      { 'err' : string }
  >,
  'updateZoneBoundaries' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];