/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TeamMember = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'principalId' : IDL.Text,
});
export const GuestId = IDL.Text;
export const WaitlistId = IDL.Text;
export const WaitlistStatus = IDL.Variant({
  'expired' : IDL.Null,
  'confirmed' : IDL.Null,
  'offered' : IDL.Null,
  'waiting' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const WaitlistEntry = IDL.Record({
  'id' : WaitlistId,
  'status' : WaitlistStatus,
  'date' : IDL.Text,
  'joinedAt' : Timestamp,
  'notifiedAt' : IDL.Opt(Timestamp),
  'notes' : IDL.Opt(IDL.Text),
  'requestedTime' : IDL.Opt(IDL.Text),
  'partySize' : IDL.Nat,
  'guestId' : GuestId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TableId = IDL.Text;
export const ReservationId = IDL.Text;
export const TableAssignment = IDL.Record({
  'assignedAt' : Timestamp,
  'seatCount' : IDL.Nat,
  'tableId' : TableId,
  'guestName' : IDL.Text,
  'reservationId' : ReservationId,
});
export const TableStatus = IDL.Variant({
  'occupied' : IDL.Null,
  'reserved' : IDL.Null,
  'empty' : IDL.Null,
  'unavailable' : IDL.Null,
});
export const Table = IDL.Record({
  'x' : IDL.Int,
  'y' : IDL.Int,
  'id' : TableId,
  'status' : TableStatus,
  'name' : IDL.Text,
  'seatCount' : IDL.Opt(IDL.Nat),
  'guestName' : IDL.Opt(IDL.Text),
  'groupId' : IDL.Opt(IDL.Text),
  'capacity' : IDL.Nat,
  'reservationId' : IDL.Opt(ReservationId),
});
export const ExperienceId = IDL.Text;
export const Experience = IDL.Record({
  'id' : ExperienceId,
  'maxCapacity' : IDL.Nat,
  'name' : IDL.Text,
  'pricePerPerson' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Guest = IDL.Record({
  'id' : GuestId,
  'reservationIds' : IDL.Vec(ReservationId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const ReservationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'late' : IDL.Null,
  'seated' : IDL.Null,
  'waitlist' : IDL.Null,
  'departed' : IDL.Null,
  'confirmed' : IDL.Null,
  'not_arrived' : IDL.Null,
});
export const Reservation = IDL.Record({
  'id' : ReservationId,
  'status' : ReservationStatus,
  'experienceId' : IDL.Opt(ExperienceId),
  'date' : IDL.Text,
  'specialRequests' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'time' : IDL.Text,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'partySize' : IDL.Nat,
  'guestId' : GuestId,
});
export const SeasonalPeriod = IDL.Record({
  'id' : IDL.Text,
  'dateTo' : IDL.Text,
  'autoActivate' : IDL.Bool,
  'name' : IDL.Text,
  'capacityOverride' : IDL.Opt(IDL.Nat),
  'activatedZones' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'dateFrom' : IDL.Text,
});
export const TimeSlotStatus = IDL.Variant({
  'full' : IDL.Null,
  'available' : IDL.Null,
  'limited' : IDL.Null,
});
export const TimeSlot = IDL.Record({
  'status' : TimeSlotStatus,
  'time' : IDL.Text,
  'totalSeats' : IDL.Nat,
  'availableSeats' : IDL.Nat,
});
export const IntegrationSettings = IDL.Record({
  'mollieEnabled' : IDL.Bool,
  'calendarSyncEnabled' : IDL.Bool,
  'stripePublicKey' : IDL.Text,
  'stripeEnabled' : IDL.Bool,
  'apiKey' : IDL.Text,
  'posSystem' : IDL.Opt(IDL.Text),
});
export const NotificationSettings = IDL.Record({
  'sendReminderEmail' : IDL.Bool,
  'waitlistAutoActivate' : IDL.Bool,
  'sendCancellationEmail' : IDL.Bool,
  'reminderHoursBefore' : IDL.Vec(IDL.Nat),
  'sendConfirmationEmail' : IDL.Bool,
});
export const CustomQuestion = IDL.Record({
  'id' : IDL.Text,
  'labelText' : IDL.Text,
  'questionType' : IDL.Variant({ 'text' : IDL.Null, 'dropdown' : IDL.Null }),
  'required' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
});
export const GuestFormSettings = IDL.Record({
  'requireAllergies' : IDL.Bool,
  'requireDietPreferences' : IDL.Bool,
  'requirePhone' : IDL.Bool,
  'customQuestions' : IDL.Vec(CustomQuestion),
});
export const DayOfWeek = IDL.Nat;
export const ZoneCapacity = IDL.Record({
  'zoneName' : IDL.Text,
  'maxGuests' : IDL.Nat,
});
export const TableType = IDL.Record({
  'count' : IDL.Nat,
  'typeName' : IDL.Text,
  'capacity' : IDL.Nat,
});
export const ReservationRules = IDL.Record({
  'maxStayMinutesDinner' : IDL.Nat,
  'maxPartySize' : IDL.Nat,
  'maxStayMinutesLunch' : IDL.Nat,
  'advanceBookingDays' : IDL.Nat,
  'noShowFeeEur' : IDL.Nat,
  'minPartySize' : IDL.Nat,
  'depositAmountEur' : IDL.Nat,
  'depositRequiredAbovePartySize' : IDL.Nat,
  'depositRequired' : IDL.Bool,
  'cancellationHoursBeforeFree' : IDL.Nat,
});
export const OccupancySettings = IDL.Record({
  'globalCeilingPercent' : IDL.Nat,
  'maxGuestsPerReservationMax' : IDL.Nat,
  'maxGuestsPerReservationMin' : IDL.Nat,
});
export const BrandingSettings = IDL.Record({
  'confirmationText' : IDL.Text,
  'primaryColor' : IDL.Text,
  'accentColor' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'defaultLanguage' : IDL.Text,
  'welcomeText' : IDL.Text,
});
export const ClosingDay = IDL.Record({
  'date' : IDL.Text,
  'serviceId' : IDL.Opt(IDL.Text),
  'reason' : IDL.Text,
});
export const ServiceHours = IDL.Record({
  'id' : IDL.Text,
  'closeTime' : IDL.Text,
  'maxCapacity' : IDL.Nat,
  'name' : IDL.Text,
  'openTime' : IDL.Text,
  'enabledDays' : IDL.Vec(DayOfWeek),
});
export const RestaurantExtendedConfig = IDL.Record({
  'timezone' : IDL.Text,
  'integrations' : IntegrationSettings,
  'notifications' : NotificationSettings,
  'openingHour' : IDL.Nat,
  'guestForm' : GuestFormSettings,
  'fixedClosingDays' : IDL.Vec(DayOfWeek),
  'logoUrl' : IDL.Opt(IDL.Text),
  'zones' : IDL.Vec(ZoneCapacity),
  'tableTypes' : IDL.Vec(TableType),
  'reservationRules' : ReservationRules,
  'currency' : IDL.Text,
  'restaurantName' : IDL.Text,
  'closingHour' : IDL.Nat,
  'contactEmail' : IDL.Text,
  'occupancySettings' : IDL.Opt(OccupancySettings),
  'branding' : BrandingSettings,
  'exceptionalClosingDays' : IDL.Vec(ClosingDay),
  'services' : IDL.Vec(ServiceHours),
  'totalSeatsPerSlot' : IDL.Nat,
  'slotIntervalMinutes' : IDL.Nat,
  'contactPhone' : IDL.Text,
});
export const FloorState = IDL.Record({
  'tables' : IDL.Vec(Table),
  'updatedAt' : Timestamp,
});
export const KPIs = IDL.Record({
  'avgPartySize' : IDL.Nat,
  'occupancyPct' : IDL.Nat,
  'todayCoversPerService' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'todayReservationCount' : IDL.Nat,
  'noShowCount' : IDL.Nat,
});
export const SuggestionAccuracyStats = IDL.Record({
  'periodDays' : IDL.Nat,
  'acceptedCount' : IDL.Nat,
  'acceptanceRatePct' : IDL.Float64,
  'totalSuggestions' : IDL.Nat,
  'rejectedCount' : IDL.Nat,
});
export const ReservationFilter = IDL.Record({
  'status' : IDL.Opt(ReservationStatus),
  'date' : IDL.Opt(IDL.Text),
  'guestId' : IDL.Opt(GuestId),
});
export const ReservationSummary = IDL.Record({
  'date' : IDL.Text,
  'time' : IDL.Text,
  'tableId' : IDL.Text,
  'partySize' : IDL.Nat,
});
export const AISeatingSuggestion = IDL.Record({
  'suggestionId' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'reasoning' : IDL.Text,
  'zonePreference' : IDL.Opt(IDL.Text),
  'partySize' : IDL.Nat,
  'confidence' : IDL.Float64,
  'suggestedTableIds' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : TeamMember, 'err' : IDL.Text })],
      [],
    ),
  'addToWaitlist' : IDL.Func(
      [GuestId, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [WaitlistEntry],
      [],
    ),
  'askAI' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignReservationToTable' : IDL.Func(
      [TableId, ReservationId],
      [IDL.Variant({ 'ok' : TableAssignment, 'err' : IDL.Text })],
      [],
    ),
  'assignReservationToTableWithDetails' : IDL.Func(
      [TableId, ReservationId, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : TableAssignment, 'err' : IDL.Text })],
      [],
    ),
  'autoAssignTable' : IDL.Func(
      [ReservationId, IDL.Nat],
      [IDL.Variant({ 'ok' : Table, 'err' : IDL.Text })],
      [],
    ),
  'cancelReservation' : IDL.Func([ReservationId], [], []),
  'createExperience' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [Experience],
      [],
    ),
  'createGuest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Guest],
      [],
    ),
  'createReservation' : IDL.Func(
      [
        GuestId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(ExperienceId),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Reservation],
      [],
    ),
  'createReservationWithDetails' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : Reservation, 'err' : IDL.Text })],
      [],
    ),
  'createTable' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Int, IDL.Int],
      [IDL.Variant({ 'ok' : Table, 'err' : IDL.Text })],
      [],
    ),
  'deleteSeasonalPeriod' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteTable' : IDL.Func(
      [TableId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'findBestTable' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Text)],
      [IDL.Opt(Table)],
      ['query'],
    ),
  'findBestTableForReservation' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Table)],
      ['query'],
    ),
  'getAISuggestions' : IDL.Func(
      [IDL.Opt(GuestId), IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
      [],
    ),
  'getActiveSeason' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SeasonalPeriod)],
      ['query'],
    ),
  'getActiveZonesForDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAvailableSlots' : IDL.Func([IDL.Text], [IDL.Vec(TimeSlot)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExtendedConfig' : IDL.Func([], [RestaurantExtendedConfig], ['query']),
  'getFloorState' : IDL.Func([], [FloorState], ['query']),
  'getGuest' : IDL.Func([GuestId], [IDL.Opt(Guest)], ['query']),
  'getKPIs' : IDL.Func([], [KPIs], ['query']),
  'getReservation' : IDL.Func(
      [ReservationId],
      [IDL.Opt(Reservation)],
      ['query'],
    ),
  'getRestaurantConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'openingHour' : IDL.Nat,
          'restaurantName' : IDL.Text,
          'closingHour' : IDL.Nat,
          'totalSeatsPerSlot' : IDL.Nat,
          'slotIntervalMinutes' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSeasonalPeriods' : IDL.Func([], [IDL.Vec(SeasonalPeriod)], ['query']),
  'getSuggestionAccuracyStats' : IDL.Func(
      [IDL.Nat],
      [SuggestionAccuracyStats],
      ['query'],
    ),
  'getTables' : IDL.Func([], [IDL.Vec(Table)], ['query']),
  'getWaitlist' : IDL.Func([IDL.Text], [IDL.Vec(WaitlistEntry)], ['query']),
  'getWaitlistEntry' : IDL.Func(
      [WaitlistId],
      [IDL.Opt(WaitlistEntry)],
      ['query'],
    ),
  'groupTables' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Table), 'err' : IDL.Text })],
      [],
    ),
  'hasOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'listExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'listGuests' : IDL.Func([], [IDL.Vec(Guest)], ['query']),
  'listReservations' : IDL.Func(
      [ReservationFilter],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'listTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'offerWaitlistSpot' : IDL.Func([WaitlistId], [], []),
  'recordSuggestionFeedback' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeTeamMember' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeWaitlistEntry' : IDL.Func(
      [WaitlistId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'reofferWaitlistSpot' : IDL.Func(
      [WaitlistId],
      [IDL.Variant({ 'ok' : WaitlistEntry, 'err' : IDL.Text })],
      [],
    ),
  'saveSeasonalPeriod' : IDL.Func(
      [SeasonalPeriod],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'searchGuests' : IDL.Func([IDL.Text], [IDL.Vec(Guest)], ['query']),
  'setOwner' : IDL.Func([IDL.Principal], [], []),
  'setTableStatus' : IDL.Func(
      [TableId, TableStatus],
      [IDL.Variant({ 'ok' : Table, 'err' : IDL.Text })],
      [],
    ),
  'suggestTable' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Vec(ReservationSummary),
      ],
      [IDL.Variant({ 'ok' : AISeatingSuggestion, 'err' : IDL.Text })],
      [],
    ),
  'toggleSeasonalPeriod' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unassignTable' : IDL.Func(
      [TableId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'ungroupTables' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Table), 'err' : IDL.Text })],
      [],
    ),
  'updateBrandingSettings' : IDL.Func(
      [BrandingSettings],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCapacitySettings' : IDL.Func(
      [
        IDL.Vec(ZoneCapacity),
        IDL.Vec(TableType),
        IDL.Opt(OccupancySettings),
        IDL.Nat,
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateExceptionalClosingDays' : IDL.Func(
      [IDL.Vec(DayOfWeek), IDL.Vec(ClosingDay)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateExperience' : IDL.Func([Experience], [], []),
  'updateGeneralInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateGuestFormSettings' : IDL.Func(
      [GuestFormSettings],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateGuestTags' : IDL.Func([GuestId, IDL.Vec(IDL.Text)], [], []),
  'updateIntegrationSettings' : IDL.Func(
      [IntegrationSettings],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateNotificationSettings' : IDL.Func(
      [NotificationSettings],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateReservation' : IDL.Func(
      [ReservationId, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : Reservation, 'err' : IDL.Text })],
      [],
    ),
  'updateReservationRules' : IDL.Func(
      [ReservationRules],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateReservationStatus' : IDL.Func(
      [ReservationId, ReservationStatus],
      [],
      [],
    ),
  'updateRestaurantConfig' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateServiceHours' : IDL.Func(
      [IDL.Vec(ServiceHours)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateTablePosition' : IDL.Func(
      [TableId, IDL.Int, IDL.Int],
      [IDL.Variant({ 'ok' : Table, 'err' : IDL.Text })],
      [],
    ),
  'updateTeamMemberRole' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateWaitlistEntry' : IDL.Func(
      [WaitlistId, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : WaitlistEntry, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TeamMember = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const GuestId = IDL.Text;
  const WaitlistId = IDL.Text;
  const WaitlistStatus = IDL.Variant({
    'expired' : IDL.Null,
    'confirmed' : IDL.Null,
    'offered' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const WaitlistEntry = IDL.Record({
    'id' : WaitlistId,
    'status' : WaitlistStatus,
    'date' : IDL.Text,
    'joinedAt' : Timestamp,
    'notifiedAt' : IDL.Opt(Timestamp),
    'notes' : IDL.Opt(IDL.Text),
    'requestedTime' : IDL.Opt(IDL.Text),
    'partySize' : IDL.Nat,
    'guestId' : GuestId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TableId = IDL.Text;
  const ReservationId = IDL.Text;
  const TableAssignment = IDL.Record({
    'assignedAt' : Timestamp,
    'seatCount' : IDL.Nat,
    'tableId' : TableId,
    'guestName' : IDL.Text,
    'reservationId' : ReservationId,
  });
  const TableStatus = IDL.Variant({
    'occupied' : IDL.Null,
    'reserved' : IDL.Null,
    'empty' : IDL.Null,
    'unavailable' : IDL.Null,
  });
  const Table = IDL.Record({
    'x' : IDL.Int,
    'y' : IDL.Int,
    'id' : TableId,
    'status' : TableStatus,
    'name' : IDL.Text,
    'seatCount' : IDL.Opt(IDL.Nat),
    'guestName' : IDL.Opt(IDL.Text),
    'groupId' : IDL.Opt(IDL.Text),
    'capacity' : IDL.Nat,
    'reservationId' : IDL.Opt(ReservationId),
  });
  const ExperienceId = IDL.Text;
  const Experience = IDL.Record({
    'id' : ExperienceId,
    'maxCapacity' : IDL.Nat,
    'name' : IDL.Text,
    'pricePerPerson' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Guest = IDL.Record({
    'id' : GuestId,
    'reservationIds' : IDL.Vec(ReservationId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const ReservationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'late' : IDL.Null,
    'seated' : IDL.Null,
    'waitlist' : IDL.Null,
    'departed' : IDL.Null,
    'confirmed' : IDL.Null,
    'not_arrived' : IDL.Null,
  });
  const Reservation = IDL.Record({
    'id' : ReservationId,
    'status' : ReservationStatus,
    'experienceId' : IDL.Opt(ExperienceId),
    'date' : IDL.Text,
    'specialRequests' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'time' : IDL.Text,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'partySize' : IDL.Nat,
    'guestId' : GuestId,
  });
  const SeasonalPeriod = IDL.Record({
    'id' : IDL.Text,
    'dateTo' : IDL.Text,
    'autoActivate' : IDL.Bool,
    'name' : IDL.Text,
    'capacityOverride' : IDL.Opt(IDL.Nat),
    'activatedZones' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'dateFrom' : IDL.Text,
  });
  const TimeSlotStatus = IDL.Variant({
    'full' : IDL.Null,
    'available' : IDL.Null,
    'limited' : IDL.Null,
  });
  const TimeSlot = IDL.Record({
    'status' : TimeSlotStatus,
    'time' : IDL.Text,
    'totalSeats' : IDL.Nat,
    'availableSeats' : IDL.Nat,
  });
  const IntegrationSettings = IDL.Record({
    'mollieEnabled' : IDL.Bool,
    'calendarSyncEnabled' : IDL.Bool,
    'stripePublicKey' : IDL.Text,
    'stripeEnabled' : IDL.Bool,
    'apiKey' : IDL.Text,
    'posSystem' : IDL.Opt(IDL.Text),
  });
  const NotificationSettings = IDL.Record({
    'sendReminderEmail' : IDL.Bool,
    'waitlistAutoActivate' : IDL.Bool,
    'sendCancellationEmail' : IDL.Bool,
    'reminderHoursBefore' : IDL.Vec(IDL.Nat),
    'sendConfirmationEmail' : IDL.Bool,
  });
  const CustomQuestion = IDL.Record({
    'id' : IDL.Text,
    'labelText' : IDL.Text,
    'questionType' : IDL.Variant({ 'text' : IDL.Null, 'dropdown' : IDL.Null }),
    'required' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
  });
  const GuestFormSettings = IDL.Record({
    'requireAllergies' : IDL.Bool,
    'requireDietPreferences' : IDL.Bool,
    'requirePhone' : IDL.Bool,
    'customQuestions' : IDL.Vec(CustomQuestion),
  });
  const DayOfWeek = IDL.Nat;
  const ZoneCapacity = IDL.Record({
    'zoneName' : IDL.Text,
    'maxGuests' : IDL.Nat,
  });
  const TableType = IDL.Record({
    'count' : IDL.Nat,
    'typeName' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  const ReservationRules = IDL.Record({
    'maxStayMinutesDinner' : IDL.Nat,
    'maxPartySize' : IDL.Nat,
    'maxStayMinutesLunch' : IDL.Nat,
    'advanceBookingDays' : IDL.Nat,
    'noShowFeeEur' : IDL.Nat,
    'minPartySize' : IDL.Nat,
    'depositAmountEur' : IDL.Nat,
    'depositRequiredAbovePartySize' : IDL.Nat,
    'depositRequired' : IDL.Bool,
    'cancellationHoursBeforeFree' : IDL.Nat,
  });
  const OccupancySettings = IDL.Record({
    'globalCeilingPercent' : IDL.Nat,
    'maxGuestsPerReservationMax' : IDL.Nat,
    'maxGuestsPerReservationMin' : IDL.Nat,
  });
  const BrandingSettings = IDL.Record({
    'confirmationText' : IDL.Text,
    'primaryColor' : IDL.Text,
    'accentColor' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'defaultLanguage' : IDL.Text,
    'welcomeText' : IDL.Text,
  });
  const ClosingDay = IDL.Record({
    'date' : IDL.Text,
    'serviceId' : IDL.Opt(IDL.Text),
    'reason' : IDL.Text,
  });
  const ServiceHours = IDL.Record({
    'id' : IDL.Text,
    'closeTime' : IDL.Text,
    'maxCapacity' : IDL.Nat,
    'name' : IDL.Text,
    'openTime' : IDL.Text,
    'enabledDays' : IDL.Vec(DayOfWeek),
  });
  const RestaurantExtendedConfig = IDL.Record({
    'timezone' : IDL.Text,
    'integrations' : IntegrationSettings,
    'notifications' : NotificationSettings,
    'openingHour' : IDL.Nat,
    'guestForm' : GuestFormSettings,
    'fixedClosingDays' : IDL.Vec(DayOfWeek),
    'logoUrl' : IDL.Opt(IDL.Text),
    'zones' : IDL.Vec(ZoneCapacity),
    'tableTypes' : IDL.Vec(TableType),
    'reservationRules' : ReservationRules,
    'currency' : IDL.Text,
    'restaurantName' : IDL.Text,
    'closingHour' : IDL.Nat,
    'contactEmail' : IDL.Text,
    'occupancySettings' : IDL.Opt(OccupancySettings),
    'branding' : BrandingSettings,
    'exceptionalClosingDays' : IDL.Vec(ClosingDay),
    'services' : IDL.Vec(ServiceHours),
    'totalSeatsPerSlot' : IDL.Nat,
    'slotIntervalMinutes' : IDL.Nat,
    'contactPhone' : IDL.Text,
  });
  const FloorState = IDL.Record({
    'tables' : IDL.Vec(Table),
    'updatedAt' : Timestamp,
  });
  const KPIs = IDL.Record({
    'avgPartySize' : IDL.Nat,
    'occupancyPct' : IDL.Nat,
    'todayCoversPerService' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'todayReservationCount' : IDL.Nat,
    'noShowCount' : IDL.Nat,
  });
  const SuggestionAccuracyStats = IDL.Record({
    'periodDays' : IDL.Nat,
    'acceptedCount' : IDL.Nat,
    'acceptanceRatePct' : IDL.Float64,
    'totalSuggestions' : IDL.Nat,
    'rejectedCount' : IDL.Nat,
  });
  const ReservationFilter = IDL.Record({
    'status' : IDL.Opt(ReservationStatus),
    'date' : IDL.Opt(IDL.Text),
    'guestId' : IDL.Opt(GuestId),
  });
  const ReservationSummary = IDL.Record({
    'date' : IDL.Text,
    'time' : IDL.Text,
    'tableId' : IDL.Text,
    'partySize' : IDL.Nat,
  });
  const AISeatingSuggestion = IDL.Record({
    'suggestionId' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'reasoning' : IDL.Text,
    'zonePreference' : IDL.Opt(IDL.Text),
    'partySize' : IDL.Nat,
    'confidence' : IDL.Float64,
    'suggestedTableIds' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : TeamMember, 'err' : IDL.Text })],
        [],
      ),
    'addToWaitlist' : IDL.Func(
        [GuestId, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [WaitlistEntry],
        [],
      ),
    'askAI' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignReservationToTable' : IDL.Func(
        [TableId, ReservationId],
        [IDL.Variant({ 'ok' : TableAssignment, 'err' : IDL.Text })],
        [],
      ),
    'assignReservationToTableWithDetails' : IDL.Func(
        [TableId, ReservationId, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : TableAssignment, 'err' : IDL.Text })],
        [],
      ),
    'autoAssignTable' : IDL.Func(
        [ReservationId, IDL.Nat],
        [IDL.Variant({ 'ok' : Table, 'err' : IDL.Text })],
        [],
      ),
    'cancelReservation' : IDL.Func([ReservationId], [], []),
    'createExperience' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [Experience],
        [],
      ),
    'createGuest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Guest],
        [],
      ),
    'createReservation' : IDL.Func(
        [
          GuestId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(ExperienceId),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Reservation],
        [],
      ),
    'createReservationWithDetails' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : Reservation, 'err' : IDL.Text })],
        [],
      ),
    'createTable' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Int, IDL.Int],
        [IDL.Variant({ 'ok' : Table, 'err' : IDL.Text })],
        [],
      ),
    'deleteSeasonalPeriod' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteTable' : IDL.Func(
        [TableId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'findBestTable' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Text)],
        [IDL.Opt(Table)],
        ['query'],
      ),
    'findBestTableForReservation' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Table)],
        ['query'],
      ),
    'getAISuggestions' : IDL.Func(
        [IDL.Opt(GuestId), IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
        [],
      ),
    'getActiveSeason' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SeasonalPeriod)],
        ['query'],
      ),
    'getActiveZonesForDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAvailableSlots' : IDL.Func([IDL.Text], [IDL.Vec(TimeSlot)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExtendedConfig' : IDL.Func([], [RestaurantExtendedConfig], ['query']),
    'getFloorState' : IDL.Func([], [FloorState], ['query']),
    'getGuest' : IDL.Func([GuestId], [IDL.Opt(Guest)], ['query']),
    'getKPIs' : IDL.Func([], [KPIs], ['query']),
    'getReservation' : IDL.Func(
        [ReservationId],
        [IDL.Opt(Reservation)],
        ['query'],
      ),
    'getRestaurantConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'openingHour' : IDL.Nat,
            'restaurantName' : IDL.Text,
            'closingHour' : IDL.Nat,
            'totalSeatsPerSlot' : IDL.Nat,
            'slotIntervalMinutes' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSeasonalPeriods' : IDL.Func([], [IDL.Vec(SeasonalPeriod)], ['query']),
    'getSuggestionAccuracyStats' : IDL.Func(
        [IDL.Nat],
        [SuggestionAccuracyStats],
        ['query'],
      ),
    'getTables' : IDL.Func([], [IDL.Vec(Table)], ['query']),
    'getWaitlist' : IDL.Func([IDL.Text], [IDL.Vec(WaitlistEntry)], ['query']),
    'getWaitlistEntry' : IDL.Func(
        [WaitlistId],
        [IDL.Opt(WaitlistEntry)],
        ['query'],
      ),
    'groupTables' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Table), 'err' : IDL.Text })],
        [],
      ),
    'hasOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'listExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'listGuests' : IDL.Func([], [IDL.Vec(Guest)], ['query']),
    'listReservations' : IDL.Func(
        [ReservationFilter],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'listTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'offerWaitlistSpot' : IDL.Func([WaitlistId], [], []),
    'recordSuggestionFeedback' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeTeamMember' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeWaitlistEntry' : IDL.Func(
        [WaitlistId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'reofferWaitlistSpot' : IDL.Func(
        [WaitlistId],
        [IDL.Variant({ 'ok' : WaitlistEntry, 'err' : IDL.Text })],
        [],
      ),
    'saveSeasonalPeriod' : IDL.Func(
        [SeasonalPeriod],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'searchGuests' : IDL.Func([IDL.Text], [IDL.Vec(Guest)], ['query']),
    'setOwner' : IDL.Func([IDL.Principal], [], []),
    'setTableStatus' : IDL.Func(
        [TableId, TableStatus],
        [IDL.Variant({ 'ok' : Table, 'err' : IDL.Text })],
        [],
      ),
    'suggestTable' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Vec(ReservationSummary),
        ],
        [IDL.Variant({ 'ok' : AISeatingSuggestion, 'err' : IDL.Text })],
        [],
      ),
    'toggleSeasonalPeriod' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unassignTable' : IDL.Func(
        [TableId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'ungroupTables' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Table), 'err' : IDL.Text })],
        [],
      ),
    'updateBrandingSettings' : IDL.Func(
        [BrandingSettings],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCapacitySettings' : IDL.Func(
        [
          IDL.Vec(ZoneCapacity),
          IDL.Vec(TableType),
          IDL.Opt(OccupancySettings),
          IDL.Nat,
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateExceptionalClosingDays' : IDL.Func(
        [IDL.Vec(DayOfWeek), IDL.Vec(ClosingDay)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateExperience' : IDL.Func([Experience], [], []),
    'updateGeneralInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateGuestFormSettings' : IDL.Func(
        [GuestFormSettings],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateGuestTags' : IDL.Func([GuestId, IDL.Vec(IDL.Text)], [], []),
    'updateIntegrationSettings' : IDL.Func(
        [IntegrationSettings],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateNotificationSettings' : IDL.Func(
        [NotificationSettings],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateReservation' : IDL.Func(
        [ReservationId, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : Reservation, 'err' : IDL.Text })],
        [],
      ),
    'updateReservationRules' : IDL.Func(
        [ReservationRules],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateReservationStatus' : IDL.Func(
        [ReservationId, ReservationStatus],
        [],
        [],
      ),
    'updateRestaurantConfig' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateServiceHours' : IDL.Func(
        [IDL.Vec(ServiceHours)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateTablePosition' : IDL.Func(
        [TableId, IDL.Int, IDL.Int],
        [IDL.Variant({ 'ok' : Table, 'err' : IDL.Text })],
        [],
      ),
    'updateTeamMemberRole' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateWaitlistEntry' : IDL.Func(
        [WaitlistId, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : WaitlistEntry, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };